name: device_security_auth
description: "Store account authentication information protected by the local device security."
version: 1.0.0
homepage: "https://saveoursecrets.com"
repository: "https://github.com/saveoursecrets/device-security-auth"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: KeychainSigninPlugin
      macos:
        pluginClass: KeychainSigninPlugin
