name: keychain_signin
description: "Plugin that allows account sign in using the Security and LocalAuthentication frameworks."
version: 1.0.0
homepage: "https://saveoursecrets.com"
repository: "https://github.com/saveoursecrets/gui-plugins"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: KeychainSigninPlugin
      macos:
        pluginClass: KeychainSigninPlugin
